name: txdb
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  default:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Allow script to run
        run: cd v && chmod +x ./txdb

      - name: Run script
        run: cd v && ./txdb

      - name: Push
        run: |
          git config --global user.name 'nfangxu'
          git config --global user.email 'nfangxu@gmail.com'
          git add .
          git commit -am "auto commit"
          git pull && git push
